package com.rank.lexi.data.repository

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import java.net.HttpURLConnection
import java.net.URL

data class WordDefinition(
    val word: String,
    val partOfSpeech: String,
    val definition: String,
    val example: String = "",
)

object DictionaryHelper {

    private val BUILT_IN_DEFINITIONS = mapOf(
        "CRANE" to WordDefinition("CRANE", "noun", "A large, tall machine used for moving heavy objects, or a tall wading bird.", "The crane hoisted the steel beam high above the construction site."),
        "SLOTH" to WordDefinition("SLOTH", "noun", "A slow-moving nocturnal tropical American mammal, or reluctance to work.", "The three-toed sloth hung motionless from the jungle canopy."),
        "ABOUT" to WordDefinition("ABOUT", "preposition", "On the subject of; concerning; approximately.", "We talked about our travel adventures across the globe."),
        "REACT" to WordDefinition("REACT", "verb", "Respond to something in a particular way or undergo a chemical transformation.", "The students watched the copper solution react with zinc."),
        "TRACE" to WordDefinition("TRACE", "verb", "Find or discover by investigation; copy a drawing by following its lines.", "Police managed to trace the lost signal across the valley."),
        "ROAST" to WordDefinition("ROAST", "verb", "Cook by prolonged exposure to heat in an oven or over a fire.", "The aroma of roast chestnuts filled the winter market air."),
        "FLAME" to WordDefinition("FLAME", "noun", "A hot glowing body of ignited gas generated by something on fire.", "The orange flame danced brightly inside the hearth."),
        "STONE" to WordDefinition("STONE", "noun", "Hard, solid non-metallic mineral matter of which rock is made.", "The ancient fortress was built of hand-carved stone."),
        "LIGHT" to WordDefinition("LIGHT", "noun", "The natural agent that stimulates sight and makes things visible.", "Morning light broke over the distant misty mountains."),
        "SHINE" to WordDefinition("SHINE", "verb", "Give out or reflect bright light; be outstanding or excel.", "Stars shine brightly on clear, moonless autumn nights."),
        "BREAD" to WordDefinition("BREAD", "noun", "Food made of flour, water, and yeast, mixed and baked.", "Fresh artisan sourdough bread was cooling on the wooden board."),
        "WATER" to WordDefinition("WATER", "noun", "A transparent, odorless, tasteless liquid essential for all life.", "The mountain brook carried cold, crisp water down the gorge."),
        "EARTH" to WordDefinition("EARTH", "noun", "The planet on which we live; the world; soil or ground.", "The astronauts looked back at the blue marble of Earth."),
        "HEART" to WordDefinition("HEART", "noun", "The hollow muscular organ that pumps the blood through the circulatory system.", "His heart beat with excitement as the finish line came in sight."),
        "BRAIN" to WordDefinition("BRAIN", "noun", "An organ of soft nervous tissue contained in the skull of vertebrates.", "The human brain processes vast streams of sensory data every second."),
        "PLANT" to WordDefinition("PLANT", "noun", "A living organism of the kind exemplified by trees, shrubs, and herbs.", "The gardener nurtured each rare desert plant under the glass roof."),
        "SMILE" to WordDefinition("SMILE", "verb", "Form one's features into a pleased or amused expression.", "She could not help but smile when she read the heartfelt letter."),
        "DREAM" to WordDefinition("DREAM", "noun", "A series of thoughts, images, and sensations occurring in a person's mind during sleep.", "His lifelong dream was to explore the uncharted Arctic archipelago."),
        "CLOUD" to WordDefinition("CLOUD", "noun", "A visible mass of condensed watery vapour floating in the atmosphere.", "A lone white cloud drifted slowly across the azure sky."),
        "STORM" to WordDefinition("STORM", "noun", "A violent disturbance of the atmosphere with strong winds and rain or snow.", "The fishing fleet returned to port before the gathering storm broke."),
        "OCEAN" to WordDefinition("OCEAN", "noun", "A very large expanse of sea, in particular each of the main areas into which the sea is divided.", "The endless expanse of the Pacific Ocean stretched to the horizon."),
        "RIVER" to WordDefinition("RIVER", "noun", "A large natural stream of water flowing in a channel to the sea, a lake, or another river.", "The winding river carved a deep canyon through sandstone cliffs."),
        "FOREST" to WordDefinition("FOREST", "noun", "A large area covered chiefly with trees and undergrowth.", "Sunlight filtered through the dense green canopy of the redwood forest."),
        "CASTLE" to WordDefinition("CASTLE", "noun", "A large building, typically of the medieval period, fortified against attack.", "The medieval stone castle stood proud atop the rocky promontory."),
        "KNIGHT" to WordDefinition("KNIGHT", "noun", "In the Middle Ages, a man who served his sovereign or lord as a mounted man-at-arms.", "The knight wore polished plate armor and carried a heraldic shield."),
        "SHIELD" to WordDefinition("SHIELD", "noun", "A broad piece of metal, wood, or leather used as a defense against weapons.", "The bronze shield deflected the blow and protected the squad."),
        "SWORD" to WordDefinition("SWORD", "noun", "A weapon with a long metal blade and a hilt with a hand guard.", "The blacksmith forged the tempered steel sword with meticulous precision."),
        "SILVER" to WordDefinition("SILVER", "noun", "A precious shiny, greyish-white metallic chemical element.", "Antique silver cutlery glistened under the candlelight."),
        "GOLDEN" to WordDefinition("GOLDEN", "adjective", "Colored or shining like gold; marked by prosperity or excellence.", "The golden rays of sunrise illuminated the sleeping harbor."),
        "BRONZE" to WordDefinition("BRONZE", "noun", "A yellowish-brown alloy of copper with up to one-third tin.", "The winning athlete proudly accepted the Olympic bronze medal."),
        "CRYSTAL" to WordDefinition("CRYSTAL", "noun", "A piece of a homogeneous solid substance having a natural geometrically regular form.", "A quartz crystal caught the light, refracting rainbow patterns."),
        "DIAMOND" to WordDefinition("DIAMOND", "noun", "A precious stone consisting of a clear and typically colorless crystalline form of pure carbon.", "The diamond sparkled with exceptional clarity and brilliance."),
        "SHADOW" to WordDefinition("SHADOW", "noun", "A dark area or shape produced by a body coming between rays of light and a surface.", "The tall oak tree cast a comforting shadow on the warm grass."),
        "WHISPER" to WordDefinition("WHISPER", "verb", "Speak very softly using one's breath without vibrating the vocal cords.", "She leaned in close to whisper the secret passphrase."),
        "THUNDER" to WordDefinition("THUNDER", "noun", "A loud rumbling or crashing noise heard after a lightning flash.", "A sudden clap of thunder echoed through the mountain valley."),
        "HARBOR" to WordDefinition("HARBOR", "noun", "A place on the coast where vessels may find shelter.", "Sailing boats anchored peacefully in the deep-water harbor."),
        "VOYAGE" to WordDefinition("VOYAGE", "noun", "A long journey involving travel by sea or in space.", "The crew set sail on a perilous voyage into the Southern Seas."),
        "JOURNEY" to WordDefinition("JOURNEY", "noun", "An act of traveling from one place to another.", "The pilgrims embarked on a scenic journey across the desert."),
        "PUZZLE" to WordDefinition("PUZZLE", "noun", "A game, toy, or problem designed to test ingenuity or knowledge.", "Solving this challenging daily puzzle brought immense satisfaction."),
        "RIDDLE" to WordDefinition("RIDDLE", "noun", "A question or statement phrased so as to require ingenuity in ascertaining its answer.", "The sphinx posed an ancient riddle to all who sought passage."),
        "ENIGMA" to WordDefinition("ENIGMA", "noun", "A person or thing that is mysterious or difficult to understand.", "The lost city's origin remained an archaeological enigma."),
        "CIPHER" to WordDefinition("CIPHER", "noun", "A secret or disguised way of writing; a code.", "The spy deciphered the coded message using a classic Caesar cipher."),
        "LEXICON" to WordDefinition("LEXICON", "noun", "The vocabulary of a person, language, or branch of knowledge.", "The game expanded his lexicon with hundreds of articulate words."),
    )

    private val runtimeCache = java.util.concurrent.ConcurrentHashMap<String, WordDefinition>()

    /**
     * Resolves a definition for [rawWord].
     * Checks the local built-in dictionary first, then runtime cache,
     * then falls back to the online Free Dictionary API, or generates a clean linguistic entry.
     */
    suspend fun resolveDefinition(rawWord: String): WordDefinition = withContext(Dispatchers.IO) {
        val word = rawWord.trim().uppercase()
        BUILT_IN_DEFINITIONS[word]?.let { return@withContext it }
        runtimeCache[word]?.let { return@withContext it }

        // Attempt online lookup via Free Dictionary API
        try {
            val url = URL("https://api.dictionaryapi.dev/api/v2/entries/en/${word.lowercase()}")
            val connection = (url.openConnection() as HttpURLConnection).apply {
                connectTimeout = 3000
                readTimeout = 3000
                requestMethod = "GET"
                setRequestProperty("Accept", "application/json")
            }

            if (connection.responseCode == 200) {
                val jsonText = connection.inputStream.bufferedReader().use { it.readText() }
                val rootArray = JSONArray(jsonText)
                if (rootArray.length() > 0) {
                    val firstEntry = rootArray.getJSONObject(0)
                    val meanings = firstEntry.optJSONArray("meanings")
                    if (meanings != null && meanings.length() > 0) {
                        val firstMeaning = meanings.getJSONObject(0)
                        val partOfSpeech = firstMeaning.optString("partOfSpeech", "noun")
                        val definitions = firstMeaning.optJSONArray("definitions")
                        if (definitions != null && definitions.length() > 0) {
                            val firstDef = definitions.getJSONObject(0)
                            val defText = firstDef.optString("definition", "")
                            val exampleText = firstDef.optString("example", "")
                            if (defText.isNotBlank()) {
                                val resolved = WordDefinition(
                                    word = word,
                                    partOfSpeech = partOfSpeech,
                                    definition = defText,
                                    example = exampleText,
                                )
                                runtimeCache[word] = resolved
                                return@withContext resolved
                            }
                        }
                    }
                }
            }
        } catch (_: Exception) {
            // Ignore network errors and use fallback below
        }

        // Clean linguistic fallback for any valid English word
        val fallback = WordDefinition(
            word = word,
            partOfSpeech = "word",
            definition = "A ${word.length}-letter word in the LexiGuess lexicon.",
            example = "You successfully deduced the word $word in today's challenge.",
        )
        runtimeCache[word] = fallback
        fallback
    }
}
